version: '3'

services:
  myWebApp:
    image: gestion-authentication-users
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - myDbUsers
    ports:
      - 8080:8080
    volumes:
      - /data/webapp
  myDbUsers:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=dbUsers
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 3310:3310
    volumes:
      - /data/mysql
